### PR TITLE
Correct outdated clean_start helper scripts

### PR DESCRIPTION
**Pull request by cmfcmf**
I am not 100% sure, but I think my simple commands achieve the same results the scripts were supposed to do achieve. Additionally, the scripts contained the old name `masterprojectpricewars`, so they didn't work anyways.

//cc @frederike-ramin @KBorchar

### CODE REVIEW

**Comment by Bouncner** [comment]
Makes sense to me, but I am not a docker expert (actually pretty much the opposite).

So with `docker-compose rm` a complete rebuild is actually not needed right? It just cleans all state.
And with `--build` we force docker to rebuild all images?

Did I get that right?

**Comment by cmfcmf** [comment]
> Did I get that right?

Exactly, that's how I understand and tested it.

**Comment by Bouncner** [comment]
@CarstenWalther : what is your take on that?

**Comment by Bouncner** [comment]
Good point. @cmfcmf : your opinion?

**Comment by cmfcmf** [comment]
> Since these are only two commands, I would omit these scripts and write them to the readme (if not already there). What do you think about that?
> Good point. @cmfcmf : your opinion?

I agree. Because the README already kinda contains similar commands in the `Cleaning up containers and existing state` and `Updating the Docker setup` sections, I've now changed this PR to simply delete the outdated scripts.

**Pull request merged**
